const toBase64=(bytes:Uint8Array)=>{let value="";bytes.forEach(byte=>{value+=String.fromCharCode(byte)});return btoa(value)};
const decode=(value:string)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));
const hex=(buffer:ArrayBuffer)=>Array.from(new Uint8Array(buffer)).map(byte=>byte.toString(16).padStart(2,"0")).join("");
export const MAX_PERMANENT_ARCHIVE_BYTES=100*1024*1024-32;
async function responseBody(response:Response,fallback:string){const text=await response.text();if(!text)return {error:fallback};try{return JSON.parse(text)}catch{return {error:text.slice(0,300)||fallback}}}
async function masterKey(passphrase:string,salt:Uint8Array,iterations=310000){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);}
export async function queuePermanentArchive(file:File,passphrase:string,onProgress?:(value:number)=>void,mediaId?:string,albumName?:string){
 if(passphrase.length<12)throw new Error("Unlock Vault Security with your 12+ character passphrase before saving.");if(file.size>MAX_PERMANENT_ARCHIVE_BYTES)throw new Error("Files must be smaller than 100 MB to complete permanent storage.");onProgress?.(5);
 const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),wrapIv=crypto.getRandomValues(new Uint8Array(12));
 const fileKey=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt","decrypt"]),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},fileKey,await file.arrayBuffer()),rawFileKey=await crypto.subtle.exportKey("raw",fileKey),kek=await masterKey(passphrase,salt),wrappedKey=await crypto.subtle.encrypt({name:"AES-GCM",iv:wrapIv},kek,rawFileKey),payloadHash=hex(await crypto.subtle.digest("SHA-256",cipher));onProgress?.(30);
 const encryptionMetadata={schema:2,algorithm:"AES-256-GCM",keyManagement:"envelope-v1",kdf:"PBKDF2-SHA256",iterations:310000,iv:toBase64(iv),salt:toBase64(salt),keyWrap:{algorithm:"AES-256-GCM",iv:toBase64(wrapIv),ciphertext:toBase64(new Uint8Array(wrappedKey))}};
 const authorization=await fetch("/api/arweave/archive/presign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:file.name,contentType:file.type||"application/octet-stream",size:cipher.byteLength,payloadHash,mediaId,albumName,encryptionMetadata})}),authorized=await responseBody(authorization,"Archive staging failed on the server.");if(!authorization.ok)throw new Error(authorized.error||"Archive staging failed.");onProgress?.(40);
 await new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();request.open("PUT",authorized.uploadUrl);request.setRequestHeader("Content-Type","application/octet-stream");request.upload.onprogress=event=>{if(event.lengthComputable)onProgress?.(40+Math.round(event.loaded/event.total*45))};request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error("Encrypted staging upload failed."));request.onerror=()=>reject(new Error("Encrypted staging upload was interrupted."));request.send(cipher)});
 const completion=await fetch("/api/arweave/archive/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:authorized.jobId})}),completed=await responseBody(completion,"Archive queueing failed on the server.");if(!completion.ok)throw new Error(completed.error||"Archive queueing failed.");onProgress?.(100);return {jobId:authorized.jobId,payloadHash,encryptionMetadata};
}
export async function decryptArchiveCipher(cipher:ArrayBuffer,metadata:any,passphrase:string){
 const salt=decode(metadata.salt),iv=decode(metadata.iv);let key:CryptoKey;
 if(metadata.keyManagement==="envelope-v1"&&metadata.keyWrap?.ciphertext){const kek=await masterKey(passphrase,salt,Number(metadata.iterations||310000)),raw=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(metadata.keyWrap.iv)},kek,decode(metadata.keyWrap.ciphertext));key=await crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["decrypt"])}else{key=await masterKey(passphrase,salt,Number(metadata.iterations||310000))}
 return crypto.subtle.decrypt({name:"AES-GCM",iv},key,cipher);
}
export async function verifyAndDecryptArchive(job:any,passphrase:string){const verification=await fetch("/api/arweave/archive/verify/"+encodeURIComponent(job.id)),verified=await verification.json();if(!verification.ok||!verified.verified)throw new Error(verified.error||"Gateway payload hash verification failed.");const response=await fetch("https://arweave.net/"+encodeURIComponent(job.transactionId));if(!response.ok)throw new Error("Confirmed archive could not be downloaded.");const cipher=await response.arrayBuffer();if(hex(await crypto.subtle.digest("SHA-256",cipher))!==job.payloadHash)throw new Error("Downloaded archive hash mismatch.");const plain=await decryptArchiveCipher(cipher,job.encryptionMetadata||{},passphrase);return new Blob([plain],{type:job.contentType||"application/octet-stream"})}
