export interface CollectionArchive {
  id:string; name:string; transactionId:string; payloadHash:string; contentType:string; sizeBytes:number;
  albumName?:string|null;
  encryptionMetadata:{schema?:number;algorithm?:string;keyManagement?:string;kdf?:string;iterations?:number;iv?:string;salt?:string;keyWrap?:{algorithm?:string;iv?:string;ciphertext?:string}};
}
function safeJson(value:unknown){return JSON.stringify(value).replace(/</g,"\\u003c").replace(/>/g,"\\u003e").replace(/&/g,"\\u0026");}
function escapeTitle(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
export function buildArweaveCollectionHtml(input:{title:string;createdAt:string;archives:CollectionArchive[]}){
 const manifest=safeJson({schema:3,title:input.title,createdAt:input.createdAt,archives:input.archives});const title=escapeTitle(input.title);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Aeterna Vault</title><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#08040f;color:#eee3ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#291440,#08040f 55%);min-height:100vh}.wrap{max-width:1240px;margin:auto;padding:32px 18px 80px}header,.card,.album{border:1px solid #b98b45;background:rgba(20,10,35,.92);border-radius:20px;box-shadow:0 18px 60px #0008}header{padding:26px;position:sticky;top:8px;z-index:5}h1,h2,h3{font-family:Georgia,serif;color:#fff0a8;margin:.2rem 0}.muted{color:#bda8d7}.notice{margin-top:14px;padding:12px;border-radius:12px;background:#e0ae4b18;color:#ffe4a0;font-size:13px}.unlock{display:flex;gap:10px;margin-top:16px}.unlock input{min-width:0;flex:1;background:#090412;color:#fff;border:1px solid #77558f;border-radius:12px;padding:13px}.unlock button,.download{border:0;border-radius:12px;padding:12px 18px;background:linear-gradient(90deg,#efd58f,#bd8737);color:#160c20;font-weight:700;cursor:pointer}.unlock button:disabled{opacity:.5}.summary{min-height:20px;margin-top:8px;font-size:12px}.album{padding:18px;margin-top:22px}.album-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.album-count{font:11px ui-monospace,monospace;color:#d9bb77}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px;margin-top:15px}.card{padding:16px}.meta{font:11px ui-monospace,monospace;color:#d9bb77;overflow-wrap:anywhere}.preview{height:250px;border:0;border-radius:14px;background:#050208;color:#bda8d7;display:grid;place-items:center;overflow:hidden;margin:12px 0;width:100%;padding:0}.preview.ready{cursor:zoom-in}.preview img,.preview video{width:100%;height:100%;object-fit:contain}.status{min-height:20px;margin-top:9px;font-size:12px;color:#cab6df}.ok{color:#7ef0b0}.bad{color:#ff9aaa}.lightbox{position:fixed;inset:0;z-index:50;background:#020105ee;display:none;align-items:center;justify-content:center;padding:24px}.lightbox.open{display:flex}.lightbox img{max-width:96vw;max-height:92vh;object-fit:contain}.close{position:absolute;right:22px;top:18px;border:1px solid #d9bb77;background:#160c20;color:#fff0a8;border-radius:999px;width:44px;height:44px;font-size:24px;cursor:pointer}@media(max-width:600px){header{position:static}.unlock{flex-direction:column}.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><header><div class="meta">IMMORTAL VIEWER · INDEPENDENT ARWEAVE ARCHIVE</div><h1>${title}</h1><p class="muted">${input.archives.length} encrypted permanent ${input.archives.length===1?"item":"items"} · published ${input.createdAt}</p><div class="notice"><strong>Independent of Aeterna:</strong> this complete viewer and every encrypted payload are served from Arweave. No Aeterna app, account, API, or server is required. Your passphrase never leaves this browser, and every payload is SHA-256 verified before local decryption.</div><div class="unlock"><input id="master" type="password" autocomplete="off" placeholder="Archive master passphrase"><button id="unlockAll">Verify & decrypt all</button></div><div id="summary" class="summary muted">Enter the passphrase used when these files were permanently archived.</div></header><main id="albums"></main></div><div id="lightbox" class="lightbox" role="dialog" aria-modal="true" aria-label="Full-size image"><button id="close" class="close" aria-label="Close">×</button><img id="full" alt=""></div><script id="manifest" type="application/json">${manifest}</script><script>
const manifest=JSON.parse(document.getElementById("manifest").textContent),root=document.getElementById("albums"),master=document.getElementById("master"),unlockAll=document.getElementById("unlockAll"),summary=document.getElementById("summary"),lightbox=document.getElementById("lightbox"),full=document.getElementById("full");
const decode=value=>Uint8Array.from(atob(value),character=>character.charCodeAt(0)),hex=buffer=>Array.from(new Uint8Array(buffer)).map(byte=>byte.toString(16).padStart(2,"0")).join(""),escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;","'":"&#39;"}[c]));
const cards=[],groups=new Map();for(const item of manifest.archives){const album=item.albumName||"Unassigned Archive";if(!groups.has(album))groups.set(album,[]);groups.get(album).push(item)}
for(const [album,items] of groups){const section=document.createElement("section");section.className="album";section.innerHTML="<div class=album-head><h2>"+escapeHtml(album)+"</h2><span class=album-count>"+items.length+" "+(items.length===1?"ITEM":"ITEMS")+"</span></div><div class=grid></div>";const grid=section.querySelector(".grid");for(const item of items){const card=document.createElement("article");card.className="card";card.innerHTML="<h3>"+escapeHtml(item.name)+"</h3><div class=meta>"+escapeHtml(item.contentType)+" · "+Math.ceil(item.sizeBytes/1024)+" KB</div><div class=meta>TX "+escapeHtml(item.transactionId)+"</div><button class=preview type=button><span>Encrypted media</span></button><div class=status>Waiting for collection passphrase.</div>";const preview=card.querySelector(".preview"),status=card.querySelector(".status");cards.push({item,preview,status});grid.append(card)}root.append(section)}
async function decrypt(entry,passphrase){const item=entry.item,status=entry.status,preview=entry.preview;status.className="status";status.textContent="Downloading and verifying…";try{const response=await fetch("https://arweave.net/"+encodeURIComponent(item.transactionId));if(!response.ok)throw new Error("Gateway HTTP "+response.status);const cipher=await response.arrayBuffer(),digest=hex(await crypto.subtle.digest("SHA-256",cipher));if(digest!==item.payloadHash)throw new Error("Ciphertext hash mismatch");const metadata=item.encryptionMetadata||{},material=await crypto.subtle.importKey("raw",new TextEncoder().encode(passphrase),"PBKDF2",false,["deriveKey"]),master=await crypto.subtle.deriveKey({name:"PBKDF2",salt:decode(metadata.salt),iterations:Number(metadata.iterations||310000),hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["decrypt"]);let key=master;if(metadata.keyManagement==="envelope-v1"&&metadata.keyWrap?.ciphertext){const raw=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(metadata.keyWrap.iv)},master,decode(metadata.keyWrap.ciphertext));key=await crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["decrypt"])}const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(metadata.iv)},key,cipher),blob=new Blob([plain],{type:item.contentType||"application/octet-stream"}),url=URL.createObjectURL(blob);preview.innerHTML="";if(item.contentType.startsWith("image/")){const media=document.createElement("img");media.src=url;media.alt=item.name;preview.append(media);preview.classList.add("ready");preview.onclick=()=>{full.src=url;full.alt=item.name;lightbox.classList.add("open")}}else if(item.contentType.startsWith("video/")){const media=document.createElement("video");media.src=url;media.controls=true;preview.append(media);preview.disabled=true}else{const link=document.createElement("a");link.className="download";link.href=url;link.download=item.name;link.textContent="Download decrypted file";preview.append(link)}status.className="status ok";status.textContent="Verified and decrypted locally.";return true}catch(error){status.className="status bad";status.textContent="Unable to decrypt. Legacy items may require their original passphrase.";return false}}
unlockAll.onclick=async()=>{const passphrase=master.value;if(!passphrase)return;unlockAll.disabled=true;let ok=0,failed=0;summary.className="summary muted";for(let index=0;index<cards.length;index++){summary.textContent="Decrypting "+(index+1)+" of "+cards.length+"…";(await decrypt(cards[index],passphrase))?ok++:failed++}summary.className="summary "+(failed?"bad":"ok");summary.textContent=ok+" decrypted"+(failed?" · "+failed+" could not be decrypted with this passphrase":" · collection unlocked");unlockAll.disabled=false};master.addEventListener("keydown",event=>{if(event.key==="Enter")unlockAll.click()});document.getElementById("close").onclick=()=>lightbox.classList.remove("open");lightbox.onclick=event=>{if(event.target===lightbox)lightbox.classList.remove("open")};addEventListener("keydown",event=>{if(event.key==="Escape")lightbox.classList.remove("open")});
</script></body></html>`;
}
