import React, { useEffect, useState } from 'react';
import { UserProfile } from '../types';
import { ArrowRight, CheckCircle2, LogOut, Mail, ShieldAlert, ShieldCheck, X } from 'lucide-react';

interface AuthModalProps { isOpen:boolean; onClose:()=>void; currentUser:UserProfile|null; onSignIn:(user:UserProfile)=>void; onSignOut:()=>void; authMode?:'signin'|'signup'; onClearDemoContent?:()=>void; onRestoreDemoContent?:()=>void; }

export const AuthModal:React.FC<AuthModalProps>=({isOpen,onClose,currentUser,onSignIn,onSignOut,authMode='signin',onClearDemoContent,onRestoreDemoContent})=>{
  const [authType,setAuthType]=useState<'signin'|'signup'>(authMode);
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [clean,setClean]=useState(true);
  useEffect(()=>setAuthType(authMode),[authMode,isOpen]);
  if(!isOpen)return null;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage(null);if(!email||!password||(authType==='signup'&&!name.trim())){setMessage('Please complete every required field.');return;}if(password.length<12){setMessage('Use at least 12 characters for your password.');return;}setBusy(true);try{const response=await fetch(authType==='signup'?'/api/auth/register':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),email,password,role:'Vault Owner'})});const result=await response.json();if(!response.ok||!result.user)throw new Error(result.error||'We could not sign you in.');if(authType==='signup'&&clean)onClearDemoContent?.();onSignIn(result.user);onClose();}catch(error){setMessage(error instanceof Error?error.message:'We could not sign you in.');}finally{setBusy(false);}};
  const reset=async()=>{if(!email){setMessage('Enter your email address first.');return;}const response=await fetch('/api/auth/request-reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const result=await response.json();setMessage(result.message||result.error||'Check your email for next steps.');};
  return <div className="fixed inset-0 z-[80] flex items-center justify-center overflow-y-auto bg-[#080312]/85 p-4 text-[#E8DDF5] backdrop-blur-md"><div role="dialog" aria-modal="true" aria-labelledby="account-dialog-title" className="relative my-auto w-full max-w-lg rounded-3xl border border-[#DFB260]/45 bg-[#160D27] p-6 shadow-2xl sm:p-8">
    <button onClick={onClose} aria-label="Close account dialog" className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-xl text-[#D8CCE8] hover:bg-white/10"><X className="h-5 w-5"/></button>
    <div className="pr-12"><p className="flex items-center gap-2 text-sm font-semibold text-[#F5D77F]"><ShieldCheck className="h-4 w-4"/>Secure account access</p><h2 id="account-dialog-title" className="mt-2 text-2xl font-bold text-[#FFF2A8] sm:text-3xl">{currentUser?'Your account':authType==='signup'?'Create your family vault':'Sign in to your vault'}</h2><p className="mt-2 text-sm leading-6 text-[#D8CCE8]">{currentUser?'Manage your account and sample content.':authType==='signup'?'Create an owner account. You can invite family members after setup.':'Use the email address and password registered to your account.'}</p></div>
    {currentUser?<div className="mt-6 space-y-5"><div className="rounded-2xl border border-[#DFB260]/30 bg-[#0A0514]/70 p-5"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#F5D77F] text-lg font-bold text-[#120B21]">{currentUser.name[0]}</span><div><h3 className="text-lg font-bold text-[#FFF2A8]">{currentUser.name}</h3><p className="text-sm text-[#D8CCE8]">{currentUser.email}</p></div></div><p className="mt-4 flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Signed in as vault owner</p></div><div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>{onClearDemoContent?.();onClose();}} className="min-h-12 rounded-xl border border-red-500/40 px-4 text-sm font-semibold text-red-200">Clear sample content</button><button onClick={()=>{onRestoreDemoContent?.();onClose();}} className="min-h-12 rounded-xl border border-[#DFB260]/40 px-4 text-sm font-semibold text-[#FFF2A8]">Restore samples</button></div><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>undefined);onSignOut();onClose();}} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-red-950/50 text-sm font-bold text-red-200"><LogOut className="h-4 w-4"/>Sign out</button></div>:<>
      <div className="mt-6 grid grid-cols-2 rounded-xl bg-[#0A0514]/70 p-1"><button onClick={()=>{setAuthType('signin');setMessage(null)}} className={`min-h-11 rounded-lg text-sm font-bold ${authType==='signin'?'bg-[#F5D77F] text-[#120B21]':'text-[#D8CCE8]'}`}>Sign in</button><button onClick={()=>{setAuthType('signup');setMessage(null)}} className={`min-h-11 rounded-lg text-sm font-bold ${authType==='signup'?'bg-[#F5D77F] text-[#120B21]':'text-[#D8CCE8]'}`}>Create account</button></div>
      {message&&<div role="alert" className="mt-4 flex gap-2 rounded-xl border border-amber-500/35 bg-amber-950/30 p-3 text-sm text-amber-100"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0"/>{message}</div>}
      <form onSubmit={submit} className="mt-5 space-y-4">{authType==='signup'&&<div><label htmlFor="signup-name" className="mb-2 block text-sm font-semibold text-[#FFF2A8]">Your name</label><input id="signup-name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} className="min-h-12 w-full rounded-xl border border-[#DFB260]/40 bg-[#0A0514] px-4 text-base text-white focus:border-[#F5D77F] focus:outline-none" required/></div>}<div><label htmlFor="account-email" className="mb-2 block text-sm font-semibold text-[#FFF2A8]">Email address</label><div className="relative"><Mail className="absolute left-3 top-3.5 h-4 w-4 text-[#C8B1E4]"/><input id="account-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" className="min-h-12 w-full rounded-xl border border-[#DFB260]/40 bg-[#0A0514] pl-9 pr-4 text-base text-white placeholder:text-[#B7A7CB] focus:border-[#F5D77F] focus:outline-none" required/></div></div><div><label htmlFor="account-password" className="mb-2 block text-sm font-semibold text-[#FFF2A8]">Password</label><input id="account-password" type="password" autoComplete={authType==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 12 characters" className="min-h-12 w-full rounded-xl border border-[#DFB260]/40 bg-[#0A0514] px-4 text-base text-white placeholder:text-[#B7A7CB] focus:border-[#F5D77F] focus:outline-none" required/>{authType==='signin'&&<button type="button" onClick={reset} className="mt-2 min-h-11 text-sm font-semibold text-[#F5D77F]">Forgot password?</button>}</div>{authType==='signup'&&<><p className="rounded-xl border border-[#DFB260]/25 bg-[#0A0514]/55 p-3 text-sm leading-6 text-[#D8CCE8]">You will be the vault owner. Trustees and family members join only through invitations you send later.</p><label className="flex items-start gap-3 text-sm text-[#D8CCE8]"><input type="checkbox" checked={clean} onChange={e=>setClean(e.target.checked)} className="mt-1 h-5 w-5"/>Start with an empty vault instead of sample memories.</label></>}<button disabled={busy} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#F5D77F] px-5 text-sm font-bold text-[#120B21] disabled:opacity-60">{busy?'Please wait…':authType==='signup'?'Create my vault':'Sign in'}<ArrowRight className="h-4 w-4"/></button></form>
    </>}
  </div></div>;
};
