import React,{useEffect,useState} from "react";
import {Copy,Eye,EyeOff,KeyRound,Loader2,ShieldCheck,Trash2} from "lucide-react";
import {decryptRecoveredPassphrase,encryptRecoveredPassphrase,generateRecoveryKey,PassphraseEnvelope} from "../lib/passphraseRecovery";
interface RecordItem extends PassphraseEnvelope{id:string;label:string;createdAt:string;lastRetrievedAt?:string|null}
export const PassphraseRecoveryVault:React.FC=()=>{
 const [records,setRecords]=useState<RecordItem[]>([]),[label,setLabel]=useState(""),[passphrase,setPassphrase]=useState(""),[recoveryKey,setRecoveryKey]=useState(""),[selectedId,setSelectedId]=useState(""),[unlockKey,setUnlockKey]=useState(""),[revealed,setRevealed]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{const response=await fetch("/api/arweave/passphrases",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Recovery records could not be loaded.");setRecords(body.records||[]);setSelectedId(current=>current||body.records?.[0]?.id||"");};useEffect(()=>{void load().catch(reason=>setError(reason.message));},[]);
 const generate=()=>{const value=generateRecoveryKey();setRecoveryKey(value);void navigator.clipboard?.writeText(value);setMessage("Recovery key generated and copied. Store it separately from Aeterna Vault.");};
 const save=async()=>{if(!label.trim()||passphrase.length<12||recoveryKey.length<20){setError("Enter a label, a 12+ character passphrase, and a strong recovery key.");return;}setBusy(true);setError("");try{const encrypted=await encryptRecoveredPassphrase(passphrase,recoveryKey),response=await fetch("/api/arweave/passphrases/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:label.trim(),...encrypted})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Recovery record could not be saved.");setLabel("");setPassphrase("");setRecoveryKey("");setMessage("Encrypted recovery record saved. Aeterna cannot decrypt it without your recovery key.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Recovery record could not be saved.");}finally{setBusy(false);}};
 const unlock=async()=>{const record=records.find(item=>item.id===selectedId);if(!record||!unlockKey)return;setBusy(true);setError("");try{setRevealed(await decryptRecoveredPassphrase(record,unlockKey));setShow(true);setMessage("Passphrase decrypted locally in this browser.");void fetch("/api/arweave/passphrases/retrieved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:record.id})});}catch{setRevealed("");setError("Unable to decrypt. Check the recovery key.");}finally{setBusy(false);}};
 const remove=async()=>{if(!selectedId||!confirm("Delete this encrypted recovery record?"))return;await fetch("/api/arweave/passphrases/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selectedId})});setSelectedId("");setRevealed("");await load();};
 return <section className="cosmic-card-gold rounded-3xl p-6"><div className="flex justify-between gap-4"><div><p className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#F5D77F]">Client-encrypted recovery</p><h2 className="mt-2 font-cinzel text-2xl text-[#FFF2A8]">Archival Passphrase Recovery Vault</h2><p className="mt-2 max-w-3xl text-xs text-[#C8B1E4]">Encryption and retrieval happen only in this browser. Aeterna stores ciphertext and cannot read your passphrase.</p></div><ShieldCheck className="h-8 w-8 text-emerald-300"/></div><div className="mt-5 grid gap-5 lg:grid-cols-2">
 <div className="rounded-2xl border border-[#DFB260]/25 bg-[#120B21]/70 p-4"><h3 className="font-cinzel text-sm text-[#FFF2A8]">Protect a passphrase</h3><div className="mt-3 grid gap-3"><input aria-label="Recovery record label" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Label, e.g. Family archive 2026" className="rounded-xl border border-[#DFB260]/40 bg-[#0B0712] p-3 text-sm"/><input aria-label="Archival passphrase to protect" type="password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} placeholder="Archival passphrase (12+ characters)" className="rounded-xl border border-[#DFB260]/40 bg-[#0B0712] p-3 text-sm"/><div className="flex gap-2"><input aria-label="Recovery key" type="password" value={recoveryKey} onChange={e=>setRecoveryKey(e.target.value)} placeholder="Separate recovery key" className="min-w-0 flex-1 rounded-xl border border-[#DFB260]/40 bg-[#0B0712] p-3 text-sm"/><button onClick={generate} className="gold-beveled-btn px-3 text-xs"><KeyRound className="mr-1 inline h-4 w-4"/>Generate</button></div><button onClick={save} disabled={busy} className="gold-filled-btn px-4 py-3 text-xs disabled:opacity-40">{busy&&<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>}Save encrypted recovery copy</button></div></div>
 <div className="rounded-2xl border border-[#DFB260]/25 bg-[#120B21]/70 p-4"><h3 className="font-cinzel text-sm text-[#FFF2A8]">Retrieve a passphrase</h3>{records.length?<div className="mt-3 grid gap-3"><select aria-label="Saved passphrase" value={selectedId} onChange={e=>{setSelectedId(e.target.value);setRevealed("");}} className="rounded-xl border border-[#DFB260]/40 bg-[#0B0712] p-3 text-sm">{records.map(record=><option key={record.id} value={record.id}>{record.label}</option>)}</select><input aria-label="Enter recovery key" type="password" value={unlockKey} onChange={e=>setUnlockKey(e.target.value)} placeholder="Enter recovery key" className="rounded-xl border border-[#DFB260]/40 bg-[#0B0712] p-3 text-sm"/><button onClick={unlock} disabled={busy||!unlockKey} className="gold-filled-btn px-4 py-3 text-xs disabled:opacity-40"><KeyRound className="mr-2 inline h-4 w-4"/>Decrypt locally</button>{revealed&&<div className="rounded-xl bg-emerald-500/10 p-3"><p className="text-[10px] uppercase text-emerald-200">Recovered passphrase</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 break-all text-sm">{show?revealed:"••••••••••••"}</code><button onClick={()=>setShow(!show)} aria-label={show?"Hide passphrase":"Show passphrase"}>{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button><button onClick={()=>void navigator.clipboard?.writeText(revealed)} aria-label="Copy passphrase"><Copy className="h-4 w-4"/></button></div></div>}<button onClick={remove} className="justify-self-end text-xs text-rose-300"><Trash2 className="mr-1 inline h-4 w-4"/>Delete recovery record</button></div>:<p className="mt-3 rounded-xl bg-black/20 p-4 text-xs text-[#C8B1E4]">No encrypted recovery records saved yet.</p>}</div></div>{message&&<p className="mt-4 rounded-xl bg-emerald-500/10 p-3 text-xs text-emerald-200">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-rose-500/10 p-3 text-xs text-rose-200">{error}</p>}<p className="mt-3 text-[10px] text-amber-100">Losing both the archival passphrase and its separate recovery key makes the archive unrecoverable. Aeterna support cannot bypass this encryption.</p></section>;
};
